'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace ASPxGridLookUpSelection


    Partial Public Class ServerSide_MultiSelect

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' ASPxHyperLink1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxHyperLink1 As Global.DevExpress.Web.ASPxHyperLink

        ''' <summary>
        ''' ASPxGridLookup1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxGridLookup1 As Global.DevExpress.Web.ASPxGridLookup

        ''' <summary>
        ''' ASPxPopupControl1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl

        ''' <summary>
        ''' ASPxListBox1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected ASPxListBox1 As Global.DevExpress.Web.ASPxListBox

        ''' <summary>
        ''' GetSelectionButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected GetSelectionButton As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' SetSelectionButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SetSelectionButton As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' AccessDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected AccessDataSource1 As Global.System.Web.UI.WebControls.AccessDataSource
    End Class
End Namespace
